Impersonation plugin
pixelart/swiftmailer-manipulator-bundle pull request #10
Opened 2016-10-18 15:07 UTC by angelov

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets |  
| Related issues/PRs | #6 
| License | MIT

This PR provides an option to change the sender's address before an email message is sent. The option is activated (for all or for any of the mailers separately) by adding the 'from_address' key in the configuration.

**Example:**

```yaml
pixelart_swiftmailer_manipulator:
    from_address: 'impersonated@example.com'
```

2016-10-18 15:16 UTC, patkar commented
Hi @angelov, many thanks for the pull request :tada: :tada: :tada: :tada: 

I will take a look later in the evening, may you already fix the failing travis test? Yes, sadly I still need to support PHP 5.4 :sob:

2016-10-18 17:36 UTC, QuingKhaos requested changes

2016-10-18 17:36 UTC, patkar commented on Swift/Plugins/ImpersonatePlugin.php
> +use Swift_Events_SendEvent;
Please remove the import and use `\Swift_Events_SendEvent` in the code below.

2016-10-18 17:36 UTC, patkar commented on Swift/Plugins/ImpersonatePlugin.php
> +     * @param string $address Address the message should be sent from
phpDoc parameter name is not consistent with the parameter :)

2016-10-18 17:36 UTC, patkar commented on Swift/Plugins/ImpersonatePlugin.php
> +        $this->originalAddresses = $message->getFrom();
May you set the original address as an `X-Swift-From` into the message (headers), like the Swiftmailer does with [sender address impersonate](https://github.com/swiftmailer/swiftmailer/blob/a6d30977565081bc9b177b627bff2e2ba905224c/lib/classes/Swift/Plugins/ImpersonatePlugin.php#L46)?

2016-10-18 17:36 UTC, patkar commented on Swift/Plugins/ImpersonatePlugin.php
> +        $message->setFrom($this->originalAddresses);
And restore the original from address from the mentioned `X-Swift-From` header above?

2016-10-18 17:36 UTC, patkar commented on Tests/DependencyInjection/Fixtures/config/yml/full.yml
> +    from_address: 'fake@example.com'
Missing newline on the end ;)

2016-10-18 17:36 UTC, patkar commented on Tests/DependencyInjection/Fixtures/config/yml/one_mailer.yml
> +            from_address: 'fake@example.com'
Missing newline on the end ;)

2016-10-18 17:36 UTC, patkar commented on DependencyInjection/PixelartSwiftmailerManipulatorExtension.php
> +    private function configureMailerImpersonation($name, array $mailer, ContainerBuilder $container)
I would call it `configureMailerFromAddress`, because that's the config name we are using and configuring on the mailer. :grin:

2016-10-18 17:38 UTC, patkar commented on Tests/Swift/Plugins/ImpersonatePluginTest.php
> +        $oldAddress = 'old@example.com';
May you add a second test which tests with an array of multiple from addresses als `$oldAddress`. Not required for the merge, just more an edge case (:

2016-10-19 10:32 UTC, angelov commented
@patkar I think you can re-check it now :)

2016-10-19 11:19 UTC, QuingKhaos approved these changes

2016-10-19 11:24 UTC, merged

2016-10-19 11:42 UTC, patkar commented
Thanks for the pull request :tada: :tada: 

And released as [1.1.0](https://github.com/pixelart/swiftmailer-manipulator-bundle/releases/tag/1.1.0) :grinning: